title: Ayodeji's Blog
author: Ayodeji Ogundare
email: hellodejisol@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  welcome to my test blog site hosted on GitHub pages.

# social links
twitter_username: dejisol # DO NOT include the @ character, or else the build will fail!
github_username:  dejisol # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
